const ARTIST_LOADING = 'ARTIST_LOADING';
const ARTIST_LOADED_SUCCESS = 'ARTIST_LOADED_SUCCESS';
const ARTIST_LOADED_FAILED = 'ARTIST_LOADED_FAILED';

export {
  ARTIST_LOADING,
  ARTIST_LOADED_SUCCESS,
  ARTIST_LOADED_FAILED,
};
