const HOME_LOADING = 'HOME_LOADING';
const ARTISTS_LOADED_SUCCESS = 'ARTISTS_LOADED_SUCCESS';
const ARTISTS_LOADED_FAILED = 'ARTISTS_LOADED_FAILED';

export {
  HOME_LOADING,
  ARTISTS_LOADED_SUCCESS,
  ARTISTS_LOADED_FAILED,
};
